# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hacked"
license = "MIT"
licenselink = "https://github.com/minoritea/hacked/blob/master/LICENSE"
description = ""
homepage = "http://github.com/minoritea/hacked"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "minoritea(Minori Tokuda)"
  homepage = "tanstaafl.0pt.jp"
